name: mot310
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=11.8
  - pip
  - pip:
    - ultralytics
    - boxmot
    - opencv-python
    - numpy==1.24.3
    - pathlib2
    - requests 